### ISSUE TITLE
Issue with dependency versions

### ISSUE THREAD

**Issue by tyler-ingebrand** [AlgebraicJulia/AlgebraicDynamics.jl#102]
Hello,

I am trying to use this project and am unable to download/compile it correctly. Using Julia 1.7.2 with no other packages installed, running "]add AlgebraicDynamics" does not build. 10 dependencies fail. 

The error is:
```
ERROR: The following 1 direct dependency failed to precompile:

AlgebraicDynamics [5fd6ff03-a254-427e-8840-ba658f502e32]

Failed to precompile AlgebraicDynamics [5fd6ff03-a254-427e-8840-ba658f502e32] to /home/undergrad/.julia/compiled/v1.7/AlgebraicDynamics/jl_blhdXu.
ERROR: LoadError: UndefVarError: DEFAULT_LINSOLVE not defined

```
which I believe is cascading and causing the other dependencies to fail. This issue is in DifferentialEquations, but only in this project. DifferentialEquations builds correctly on its own. 

I believe this is most likely a bug with the required/allowed versions.

Let me know if any other information would be helpful for reproducing this bug.

**Comment by epatters** [comment]
Can you try again on AlgebraicDynamics v0.1.6, which I just released? It seems that the necessary version dumps for DifferentialEquations had happened on master but hadn't been tagged in a release.

**Comment by tyler-ingebrand** [comment]
That worked, thank you!

 If anyone else finds this, you may also have to delete the Manifest.toml in a project when the versions change like this. In my case, it was still throwing a build error because it was expecting dependencies that have changed. After deleting it, and basically no longer requiring it to specify exact versions, it was able to pull compatible versions and work properly.
